# Generated by Django 4.1 on 2022-12-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'inscrição', 'verbose_name_plural': 'inscrições'},
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inscrição realizada em : '),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='telefone'),
        ),
    ]
